hofvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from halls import views

urlpatterns = [

    # MAIN
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),

    # AUTHENTICATION
    path('signup/', views.Signup.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # GALLERIES
    path('gallery/create/', views.CreateHall.as_view(), name='create_gallery'),
    path('gallery/<int:pk>/', views.DetailHall.as_view(), name='detail_gallery'),
    path('gallery/<int:pk>/update/', views.UpdateHall.as_view(), name='update_gallery'),
    path('gallery/<int:pk>/delete/', views.DeleteHall.as_view(), name='delete_gallery'),

    # VIDEOS
    path('gallery/<int:pk>/add/', views.add, name='add'),
    path('video/search/', views.search_video, name='search_video'),
    path('video/<int:pk>/delete/', views.DeleteVideo.as_view(), name='delete_video'),
]

# if somebody does /static, mode to STATIC_ROOT
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User

class Hall(models.Model):
    title = models.CharField(max_length=256)

    # one user has one hall
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Video(models.Model):
    title = models.CharField(max_length=256)
    url = models.URLField()
    youtube_id = models.CharField(max_length=256)

    # one call can have multiple videos
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

halls/forms.py
from .models import Video
from django import forms

# Model-based form
class VideoForm(forms.ModelForm):

    # Meta class are the attributes ModelForm needs to display
    # the form linked to the model correctly.
    class Meta:

        # you pass a model and the form is created automatically.
        model = Video

        # Specify the fields to be shown. The Hall linked as a pk is
        # not passed since it is already linked to the hall this site
        # will be called from, via its hall variable.
        fields = ['url']

        # show this labels
        labels = {'url': 'YouTube URL:'}


# Regular form
class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=256, label="Search:")

halls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
from .models import Hall, Video
from .forms import VideoForm, SearchForm
import requests
import urllib

YOUTUBE_API_KEY = 'You yt api key here'


def home(request):

    # Query the database to retrieve the last 5 created halls.
    # Halls (galleries) are ordered by -id
    recent_galleries = Hall.objects.all().order_by('-id')[:5]

    # Get some random galleries as the most popular ones
    popular_galleries = [Hall.objects.get(pk=1), Hall.objects.get(pk=2)]

    # pass everything to the template and render it
    return render(
        request,
        'halls/home.html',
        {
            'recent_galleries': recent_galleries,
            'popular_galleries': popular_galleries
        }
    )


@login_required
def dashboard(request):

    # get all hall objects of the logged in user
    galleries = Hall.objects.filter(user=request.user)

    # render them as a context dictionary and return the view
    return render(request, 'halls/dashboard.html', {'galleries': galleries})


@login_required
def add(request, pk):

    # Call for the formset we just created
    form = VideoForm()

    # create the search videos form
    search_form = SearchForm()

    # Using the PK, get the current gallery
    gallery = Hall.objects.get(pk=pk)

    # A user can only add videos to their gallery
    if not gallery.user == request.user:

        raise Http404

    # If we get passed the previous if, then this is the correct user
    # in the correct gallery (the user in their gallery)
    if request.method == 'POST':

        # create the Form with the request POST data
        form = VideoForm(request.POST)

        # try to validate
        if form.is_valid():

            # create a video object
            video = Video()

            # We have the PK of the hall object in the params, we need
            # to go get it from the DB:
            video.hall = gallery

            # cleaned_data returns a dictionary with the valid user input
            video.url = form.cleaned_data['url']

            # Get the url and youtube_id of the video from the YT API.
            # a link is in the form of:
            # https://www.youtube.com/watch?v=XfFVIz38kho
            # Where the url is the whole link, and the id comes after v=

            # First, parse the url with the user submitted one as a param
            parsed_url = urllib.parse.urlparse(video.url)

            # grab the video's id from the 'v' parameter in the link
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')

            # if the statement was properly gotten.
            if video_id:

                # parse_qs returns is a list, where [0] the value of
                # the searched param
                video.youtube_id = video_id[0]

                # request Youtube API for the google video, passing
                # the above param as id, and the API KEY as key
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')

                # convert the response to json
                json = response.json()

                # get to the title in the JSON response.
                # It is inside 'items': 'snippet'
                title = json['items'][0]['snippet']['title']

                # assign the title to video.title
                video.title = title

                # save the form
                video.save()

                # redirect the user to its hall
                return redirect('detail_gallery', pk)

            # If we could not retrieve the statement
            else:

                # add the Error traceback of the 'url' field to
                # form's internal errors' list
                errors = form._errors.setdefault('url', ErrorList())

                # Assign some hints for the user
                errors.append('Only Youtube URLs are allowed.')

    # pass it to a template at any case
    return render(
        request,
        'halls/add.html',
        {'form': form, 'search_form': search_form, 'gallery': gallery}
    )


@ login_required
def search_video(request):

    # AJAX data comes from a GET request
    search_form = SearchForm(request.GET)

    # if we got the ajax correctly
    if search_form.is_valid():

        # get what is inside the search_term (the search input for AJAX)
        search_term = search_form.cleaned_data['search_term']

        # parse it to urllib
        encoded_search_term = urllib.parse.quote(search_term)

        # fetch the video URL using YT API KEY and the parsed
        # search term above
        response = requests.get(
            f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={encoded_search_term}&key={YOUTUBE_API_KEY}'
        )

        # Convert the response to JSON and return it as a JsonResponse
        return JsonResponse(response.json())

    # if the GET request could not be processed, also return a
    # JsonResponse, but with a failure
    return JsonResponse({'Error': 'Failed to retrieve information.'})


# A CBV to delete the videos
class DeleteVideo(LoginRequiredMixin, generic.DeleteView):

    # link the template, the model and the reverse when delete is successful
    model = Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    # a function that intercepts and overrides get_object() to perform
    # a check before returning the video object to delete.
    def get_object(self):

        # get the current video from the DB. DeleteView has the access.
        # call super().get_object() passing this class and object.
        video = super(DeleteVideo, self).get_object()

        # check for identity. If the logged in user is not the owner, 404.
        if not video.hall.user == self.request.user:
            raise Http404

        # The user is the owner, return the video and proceed with deletion.
        return video

class Signup(generic.CreateView):

    # Create and assign the user creation form
    form_class = UserCreationForm

    # If the user signed up in correctly, redirect to home, logged in
    success_url = reverse_lazy('dashboard')

    # Use as a django's default signup template for registration
    template_name = 'registration/signup.html'

    # If creates a user, autologin and redirect them to hall/create
    def form_valid(self, form):

        # Signup returns the view object we will return here later,
        # once we authenticate and log in the user.
        view = super(Signup, self).form_valid(form)

        # Get the username and the password1 from the form object
        username, password = \
            form.cleaned_data.get('username'), \
            form.cleaned_data.get('password1'),

        # Authenticate them
        user = authenticate(username=username, password=password)

        # log them in
        login(self.request, user)

        return view


class CreateHall(LoginRequiredMixin, generic.CreateView):

    # specify the model
    model = Hall

    # What fields are to be shown?
    fields = ['title']

    # Template name?
    template_name = 'halls/create_gallery.html'

    # On successful creation, reverse_lazy the user to:
    success_url = reverse_lazy('dashboard')

    # If the form is valid
    def form_valid(self, form):

        # Set up the user instance to be the request.user.
        # This adds the request user as the user variable in
        # Hall model.
        form.instance.user = self.request.user

        # Call for super(), pass this same class and this object
        # instance, and call for super().form_valid()
        super(CreateHall, self).form_valid(form)

        # Redirect them to their dashboard
        return redirect('dashboard')


# DetailView shows the details of the object you pass as a model
# by taking the int passed as a parameter to fetch it from the DB.
#   > It passes the lowercase name of the model (Hall) as the
#     object name to use in the template it renders.
class DetailHall(generic.DetailView):

    model = Hall

    template_name = 'halls/detail_gallery.html'


# The same as above, when getting a hall to update, the url will
# be /gallery/<int>/update
class UpdateHall(LoginRequiredMixin, generic.UpdateView):

    model = Hall

    template_name = 'halls/update_gallery.html'

    # Which fields to update?
    fields = ['title']

    # Where to redirect if they updated successfully?
    success_url = reverse_lazy('dashboard')

    def get_object(self):

        gallery = super(UpdateHall, self).get_object()

        if not gallery.user == self.request.user:
            raise Http404

        return gallery


class DeleteHall(LoginRequiredMixin, generic.DeleteView):

    model = Hall

    template_name = 'halls/delete_gallery.html'

    success_url = reverse_lazy('dashboard')

    def get_object(self):

        gallery = super(DeleteHall, self).get_object()

        if not gallery.user == self.request.user:
            raise Http404

        return gallery

halls/templates/halls/add.html
{% extends 'halls/base.html'%}

{% block content %}

<h2 class='mt-3 text-center custom-font'> Add video to {{ gallery.title }} </h2>

<form method="post" id='submit_video' class='text-center'>

  {% csrf_token %}

  {% load widget_tweaks %}

  {% for field in form %}

  <div class="form-group custom-font {% if field.errors %} alert alert-danger {% endif %}">

    {{ field.errors }}

    {{ field.label_tag }}

    {% render_field field class='form-control' %}

  </div>

  {% endfor %}

  <input type="submit" class='btn btn-primary custom-font' value="Add video">

</form>

<br>

<h2 class='text-center custom-font'> Or </h2>

<!-- Add the form to search by AJAX -->
<form class='text-center'>

  {% for field in search_form %}

  <div class="form-group custom-font">

    {{ field.errors }}

    {{ field.label_tag }}

    {% render_field field class='form-control' %}

  </div>

  {% endfor %}

</form>

<div id="search_result">

  <script>

    let delayTimer;

    $('#id_search_term').keyup(function() {

      clearTimeout(delayTimer)

      $('#search_result').text('Fetching...')

      delayTimer = setTimeout(function() {

        let text = $('#id_search_term').val()

        $.ajax({

          url: '/video/search',
          data: {
            'search_term': text
          },
          dataType: 'json',

          // data is the JSON response of YT API, a big dictionary
          success: function(data) {

            // var to hold the results
            let results = ''

            // empty the results box
            $('#search_result').text('')

            results += '<div class="row">'

            // retrieve everything inside the fetched items and for
            // each of them, append its title
            data['items'].forEach(function(video) {

              // add bootstrap for the columns the results are
              // to be displayed
              results += '<div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-4">'

              // for each column, a card to hold the results
              results += '<div class="card mb-4 shadow-md">'

              // the fetched results inside the bootstrap structure.
              // WE NEED TO EMBED THE VIDEO!
              // Go to youtube > click on a video > share > Embed
              //    > copy the iframe code
              results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/'
              + video['id']['videoId']
              + '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'

              // a div for the card body
              results += '<div class="card-body text-center custom-font"> <p class="card-text">'
                      + video['snippet']['title']
                      + '</p>'

              // add the button to add the video
              results += '<a href="#" class="btn btn-primary mb-1 custom-font" '
                      + 'onclick="addVideo(\'' + video['id']['videoId'] + '\')">'
                      + 'Add video</a>'
                      + '</div>'

              // and close the divs
              results += '</div></div>'
            })

            results += '</div>'

            // append the results to the invisible input
            $('#search_result').append(results)

          }     // end success
        })      // end AJAX
      }, 2500)  // end setTimeout
    })          // end keyup

    // a function to simulate a click on the add button on the
    // form above, to assign to the button to add video in AJAX
    function addVideo(video_id) {

      // grab the input form to add a URL manually, set the value to
      // the video_id passed as a parameter (when clicking the add
      // button on the AJAX videos)
      $('#id_url').val('https://www.youtube.com/watch?v=' + video_id)

      // grab the upper form by its id and submit it.
      $('#submit_video').submit()
    }

  </script>

</div>

{% endblock %}

halls/templates/halls/base.html
<!doctype html>
<html lang="en">
{% load static %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Viga&display=swap" rel="stylesheet">
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>RNMC Videos</title>
  </head>

  <header class="sticky-top custom-font d-flex flex-column flex-md-row align-items-center
                 p-3 px-md-4 bg-white">

    <h5 class="my-2 mr-md-auto font-weight-normal">
      <img src="{% static 'favicon.ico' %}" height="25" width="25"
        class='img-fluid mr-2 shadow-lg'>
      <a href="{% url 'home' %}" class="text-dark custom-font">
        RNMC Videos
      </a>
    </h5>

    <nav class="my-2 my-md-0 mr-md-3">

      <a class="btn btn-outline-secondary shadow" href="https://github.com/RenzoMurinaCadierno">
        Github
      </a>

      {% if user.is_authenticated %}

      <a class="btn btn-outline-info shadow" href="{% url 'dashboard' %}">
        Galleries
      </a>
      <a class="btn btn-outline-dark shadow" href="{% url 'logout' %}">
        Logout
      </a>

      {% else %}

      <a class="btn btn-outline-primary shadow" href="{% url 'signup' %}">
        Sign up
      </a>
      <a class="btn btn-outline-dark shadow" href="{% url 'login' %}">
        Log in
      </a>

      {% endif %}

    </nav>
  </header>
  <body>

    <div class="container grow">

      {% block content %}

      {% endblock %}

    </div>
  </body>
</html>

halls/templates/halls/create_gallery.html
{% extends 'halls/base.html'%}

{% block content %}

<h2 class='mt-3 text-center custom-font'> Create a gallery </h2>

{% load widget_tweaks %}

<form method="post" class='text-center mt-3'>

  {% csrf_token %}

  {% for field in form %}

  <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">

    {{ field.errors }}

    {{ field.label_tag }}

    {% render_field field class='form-control text-center' %}

    {% endfor %}

    <input type="submit" class='btn btn-primary mt-3' value="Create">

  </div>

</form>

{% endblock %}

halls/templates/halls/dashboard.html
{% extends 'halls/base.html'%}

{% block content %}

<div class="mt-3 text-center custom-font">
  <h1>
    {{ user.username }}'s galleries
  </h1>
  <a href="{% url 'create_gallery' %}" class='btn btn-primary my-3'>
    Create new gallery
  </a>
</div>

<hr>

  {% for gallery in galleries %}

  <div class="row">
    <div class="col-12 text-center custom-font">
      <h2 class='mb-3'>
        <a class='custom-font' href="{% url 'detail_gallery' gallery.id %}">
        {{ gallery.title }}
        </a>
      </h2>
      <a href="{% url 'add' gallery.id %}" class='btn btn-primary mx-2'>
        Add video
      </a>
      <a href="{% url 'update_gallery' gallery.id %}" class='btn btn-outline-primary mx-2'>
        Edit gallery
      </a>
      <a href="{% url 'delete_gallery' gallery.id %}" class='btn btn-danger mx-2'>
        Delete Gallery
      </a>
    </div>
  </div>

    <div class="row text-center">

    <!-- Grabs all videos linked to that gallery.
            > one.many_set.all in DB language-->
    {% for video in gallery.video_set.all %}

      <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-4">
        <div class="card mb-3 shadow-md">'
          <iframe width="100%" height="225"
                  src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                  gyroscope; picture-in-picture" allowfullscreen>
          </iframe>
          <div class="card-body text-center">
            <p class="card-text custom-font">
              {{ video.title }}
            </p>
          </div>
        </div>
      </div>

    {% endfor %}

    </div>

  <hr>

  {% endfor %}

{% endblock %}

halls/templates/halls/delete_gallery.html
{% extends 'halls/base.html'%}

{% block content %}

<h2 class='text-center mt-3 custom-font'> Sure to delete this gallery? </h2>

<h2 class='text-center custom-font'>
  <a href="{% url 'detail_gallery' hall.id %}">
    {{hall.title}}
  </a>
</h2>

<form method="post" class='text-center mt-3 custom-font'>

  {% csrf_token %}

  {{ form.as_p }}

  <input type="submit" class='btn btn-danger' value="Yes, delete">

  <a href="{% url 'detail_gallery' hall.id %}"
     class='btn btn-outline-primary'>
     No, go back
   </a>

</form>

{% endblock %}

halls/templates/halls/delete_video.html
{% extends 'halls/base.html'%}

{% block content %}

<h2 class='text-center mt-3 custom-font'> Sure to delete this video? </h2>

<div class="row">
  <div class="col-md-6 offset-md-3 mt-3 custom-font">
    <div class="card mb-4 shadow-md">'
      <iframe width="100%" height="225"
              src="https://www.youtube.com/embed/{{ video.youtube_id }}"
              frameborder="0" allow="accelerometer; autoplay; encrypted-media;
              gyroscope; picture-in-picture" allowfullscreen>
      </iframe>
      <div class="card-body text-center">
        <p class="card-text">
          {{ video.title }}
        </p>
      </div>
    </div>
  </div>
</div>

<form method="post" class='text-center'>

  {% csrf_token %}

  {{ form.as_p }}

  <input type="submit" class='btn btn-danger' value="Yes, delete">

  <a href="{% url 'detail_gallery' video.hall.id %}"
     class='btn btn-outline-primary'>
     No, go back
   </a>

</form>

{% endblock %}

halls/templates/halls/detail_gallery.html
{% extends 'halls/base.html'%}

{% block content %}

  <h1 class='custom-font text-center mt-3'> {{ hall.title }} </h1>

  <h4 class='text-muted custom-font text-center mb-3'>
    <em> {{ hall.user.username }}'s gallery </em>
  </h4>

  {% if user.id is hall.user.id %}

  <div class="row">
    <div class="col-12 text-center custom-font">
      <a href="{% url 'add' hall.id %}" class='btn btn-primary mx-2'>
        Add video
      </a>
      <a href="{% url 'update_gallery' hall.id %}" class='btn btn-outline-primary mx-2'>
        Edit gallery
      </a>
      <a href="{% url 'delete_gallery' hall.id %}" class='btn btn-danger mx-2'>
        Delete Gallery
      </a>
    </div>
  </div>

  {% endif %}

    <div class="row text-center">

    <!-- Grabs all videos linked to that gallery.
            > one.many_set.all in DB language-->
    {% for video in hall.video_set.all %}

      <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-4">
        <div class="card mb-3 shadow-md">'
          <iframe width="100%" height="225"
                  src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                  gyroscope; picture-in-picture" allowfullscreen>
          </iframe>
          <div class="card-body text-center">
            <p class="card-text custom-font">
              {{ video.title }}
            </p>

            {% if user.id is hall.user.id %}
              <a href="{% url 'delete_video' video.id %}" class='btn btn-outline-danger'>
                Delete
              </a>
            {% endif %}

          </div>
        </div>
      </div>

    {% endfor %}

    </div>

{% endblock %}

halls/templates/halls/home.html
{% extends 'halls/base.html'%}

{% block content %}

<section class='jumbotron text-center custom-font'>

  <h1 class='jumbotron-heading'> Welcome to RNMC Videos! </h1>

  <p class='lead text-muted mt-4'>
    <em>Log in, create galleries of yout favourite Youtube videos,
    share them with everyone.</em>
  </p>
  <p class='lead text-muted'>
  <em>That simple!</em>
  </p>
  <p>
    <a href="{% url 'create_gallery' %}"
       class='btn btn-outline-primary btn-lg mt-3 shadow'>
      Get started!
    </a>
  </p>
</section>

<div class="container">

  <h1 class='text-center custom-font'> Popular galleries </h1>

  {% for gallery in popular_galleries %}

  <div class="row mt-4">
    <div class="col-12 text-center custom-font">
      <h2 class='mb-3'>
        <a class='custom-font' href="{% url 'detail_gallery' gallery.id %}">
        {{ gallery.title }}
        </a>
        <span class='text-muted by-username'>
          by {{ gallery.user.username }}
        </span>
      </h2>
    </div>
  </div>

    <div class="row text-center">

    {% for video in gallery.video_set.all %}

      <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-4">
        <div class="card mb-3 shadow-md">'
          <iframe width="100%" height="225"
                  src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                  gyroscope; picture-in-picture" allowfullscreen>
          </iframe>
          <div class="card-body text-center">
            <p class="card-text custom-font">
              {{ video.title }}
            </p>
          </div>
        </div>
      </div>

    {% endfor %}

    </div>

  <hr>

  {% endfor %}

  <h1 class='text-center custom-font mt-4'> Recent galleries </h1>

  {% for gallery in recent_galleries %}

  <div class="row mt-4">
    <div class="col-12 text-center custom-font">
      <h2 class='mb-3'>
        <a class='custom-font' href="{% url 'detail_gallery' gallery.id %}">
        {{ gallery.title }}
        </a>
        <span class='text-muted by-username'>
          by {{ gallery.user.username }}
        </span>
      </h2>
    </div>
  </div>

    <div class="row text-center">

    {% for video in gallery.video_set.all %}

      <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-4">
        <div class="card mb-3 shadow-md">'
          <iframe width="100%" height="225"
                  src="https://www.youtube.com/embed/{{ video.youtube_id }}"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                  gyroscope; picture-in-picture" allowfullscreen>
          </iframe>
          <div class="card-body text-center">
            <p class="card-text custom-font">
              {{ video.title }}
            </p>
          </div>
        </div>
      </div>

    {% endfor %}

    </div>

  <hr>

  {% endfor %}

</div>

{% endblock %}

halls/templates/halls/update_gallery.html
{% extends 'halls/base.html'%}

{% block content %}

<h2 class='text-center mt-3 custom-font'> Edit gallery </h2>

{% load widget_tweaks %}

<form method="post" class='text-center mt-3 custom-font'>

  {% csrf_token %}

  {% for field in form %}

  <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">

    {{ field.errors }}

    {{ field.label_tag }}

    {% render_field field class='form-control text-center' %}

  {% endfor %}

    <input type="submit" class='btn btn-outline-primary mt-3' value="Update">

    <a href="{% url 'delete_gallery' hall.id %}" class='btn btn-danger mt-3'>
      Delete
    </a>

  </div>
</form>


{% endblock %}